target = "~/.local/share/rofi"
exclude = [
    '\.bub\.toml$',
    '\.unboxrc(\.ron)?$',
    '^\.git.*$',
    '\.unboxrc.*$',
    "^(README|LICEN[CS]E|COPYING).*$",
]
include = []
link_root = false
link_type = "absolute"
