target = "~/.config/uwsm"
exclude = [
    '^\.git.*$',
    '\.unboxrc(\.ron)?$',
    "^(README|LICEN[CS]E|COPYING).*$",
    '\.unboxrc.*$',
    '\.bub\.toml$',
]
include = []
link_root = false
link_type = "absolute"
