target = "~/.config/paru"
exclude = [
    '\.unboxrc(\.ron)?$',
    '^\.git.*$',
    "^(README|LICEN[CS]E|COPYING).*$",
    '\.unboxrc.*$',
    '\.bub\.toml$',
]
include = []
link_root = false
link_type = "absolute"
