version: 2

global:
  # forget policies sort by recency
  forget:
    # always keep at least 10 snapshots
    keep-last: 10
    keep-hourly: 24
    keep-daily: 7
    keep-weekly: 4
    keep-monthly: 12
    keep-yearly: 3

backends:
  dumpsite:
    type: local
    path: /mnt/Dumpsite/Autorestic Lotus/repo
    # env: AUTORESTIC_DUMPSITE_RESTIC_PASSWORD
    requireKey: true

locations:
  data-dirs:
    from:
      - /home/hunterdavenport/Documents
      - /home/hunterdavenport/Downloads
      - /home/hunterdavenport/Pictures
      - /home/hunterdavenport/Videos
    to: dumpsite
    # once a day at 4AM
    cron: '0 4 * * *'
    forget: prune
  dotfiles:
    from:
      - /home/hunterdavenport/.config/user-dirs.dirs
      - /home/hunterdavenport/.zsh
      - /home/hunterdavenport/.zshenv
      - /home/hunterdavenport/dotfiles
    to: dumpsite
    # once a day at 4AM
    cron: '0 4 * * *'
    forget: prune
  syncthing-tray-config:
    # TODO: a better syncthing setup
    hooks:
      before:
        - systemctl stop syncthing@hunterdavenport.service
      after:
        - systemctl start syncthing@hunterdavenport.service
    from:
      - /home/hunterdavenport/.local/state/syncthing
      - /home/hunterdavenport/.config/syncthingtray.ini
    to: dumpsite
    # once a day at 4AM
    cron: '0 4 * * *'
    forget: prune
